# Generated by Django 4.0.6 on 2023-04-10 21:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxDetailDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=30, verbose_name='Cliente')),
                ('code', models.CharField(max_length=10, verbose_name='Codigo')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Documento')),
                ('exists', models.CharField(max_length=1, verbose_name='Existencia')),
                ('joined', models.CharField(max_length=1, verbose_name='Agregado')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BoxDetailExpedients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_code', models.CharField(max_length=10)),
                ('client_code', models.CharField(max_length=10)),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Documento')),
                ('names', models.CharField(max_length=30)),
                ('surnames', models.CharField(max_length=30)),
                ('card_id', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=8)),
                ('exists', models.CharField(max_length=1, verbose_name='Existencia')),
                ('joined', models.CharField(max_length=1, verbose_name='Agregado')),
            ],
            options={
                'verbose_name': 'Expedient',
                'verbose_name_plural': 'Expedients',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='BoxDetailFileDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de subida')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Box_Details_File',
                'verbose_name_plural': 'Box_Detail_Files',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='BoxDetailFileExpedients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de subida')),
                ('file', models.FileField(blank=True, null=True, upload_to='expedientsAdministration/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Box_Details_File',
                'verbose_name_plural': 'Box_Detail_Files',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='BoxDetailFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de cambio')),
                ('comment', models.CharField(blank=True, max_length=300, null=True, verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'Box_Details_Follows',
                'verbose_name_plural': 'Box_Detail_Follow',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SendEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send', models.CharField(default=0, max_length=1, verbose_name='Enviado')),
                ('follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.boxdetailfollow')),
            ],
            options={
                'verbose_name': 'SendEmail',
                'verbose_name_plural': 'SendEmails',
                'ordering': ['send'],
            },
        ),
        migrations.CreateModel(
            name='Boxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_info', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Caja')),
                ('status', models.CharField(max_length=1, verbose_name='Estado')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Registro')),
                ('start_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Fin')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.branches', verbose_name='Sucursal')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.documents')),
            ],
            options={
                'verbose_name': 'Box',
                'verbose_name_plural': 'Boxes',
                'ordering': ['date_joined'],
            },
        ),
    ]
