# Generated by Django 4.0.6 on 2023-04-10 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boxes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='boxdetailfollow',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.boxes'),
        ),
        migrations.AddField(
            model_name='boxdetailfollow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boxdetailfileexpedients',
            name='expedient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.boxdetailexpedients'),
        ),
        migrations.AddField(
            model_name='boxdetailfileexpedients',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boxdetailfiledocuments',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.boxdetaildocuments'),
        ),
        migrations.AddField(
            model_name='boxdetailfiledocuments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boxdetailexpedients',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.boxes'),
        ),
        migrations.AddField(
            model_name='boxdetaildocuments',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.boxes'),
        ),
        migrations.AddField(
            model_name='boxdetaildocuments',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.documents'),
        ),
    ]
