# Generated by Django 4.0.6 on 2023-04-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_boxes_personal_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxdetailexpedients',
            name='card_id',
            field=models.CharField(max_length=14),
        ),
    ]
