# Generated by Django 4.0.6 on 2023-04-20 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_boxdetailexpedients_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxes',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now, verbose_name='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='YYYY-MM-DD'),
        ),
    ]
