# Generated by Django 4.0.6 on 2023-04-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_boxes_date_joined_alter_boxes_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxdetailexpedients',
            name='client_code',
        ),
        migrations.RemoveField(
            model_name='boxdetailexpedients',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='boxdetailexpedients',
            name='file_code',
        ),
    ]
