# Generated by Django 4.0.6 on 2022-07-30 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('responsable', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Departament',
                'verbose_name_plural': 'Departaments',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Document_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tipo Documento')),
            ],
            options={
                'verbose_name': 'Document_type',
                'verbose_name_plural': 'Documents_types',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Personals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=30)),
                ('surnames', models.CharField(max_length=30)),
                ('card_id', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personals',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Serials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Serie Documental')),
            ],
            options={
                'verbose_name': 'Serial',
                'verbose_name_plural': 'Serials',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Sub_serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Sub serie documental')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.serials')),
            ],
            options={
                'verbose_name': 'Sub_serial',
                'verbose_name_plural': 'Sub_serials',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Expedients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AREA', 'Area'), ('ARCHIVO', 'Archivo'), ('EMPRESA', 'Empresa')], default='AREA', max_length=10)),
                ('file_code', models.CharField(max_length=10)),
                ('client_code', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of', models.DateField(blank=True, null=True, verbose_name='YYYY-MM-DD')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='YYYY-MM-DD')),
                ('month_of', models.CharField(choices=[('ENERO', 'Enero'), ('FEBRERO', 'Febrero'), ('MARZO', 'Marzo'), ('ABRIL', 'Abril'), ('MAYO', 'Mayo'), ('JUNIO', 'Junio'), ('JULIO', 'Julio'), ('AGOSTO', 'Agosto'), ('SEPTIEMBRE', 'Septiembre'), ('OCTUBRE', 'Octubre'), ('NOVIEMBRE', 'Noviembre'), ('DICIEMBRE', 'Diciembre')], default='ENERO', max_length=10)),
                ('month_to', models.CharField(choices=[('ENERO', 'Enero'), ('FEBRERO', 'Febrero'), ('MARZO', 'Marzo'), ('ABRIL', 'Abril'), ('MAYO', 'Mayo'), ('JUNIO', 'Junio'), ('JULIO', 'Julio'), ('AGOSTO', 'Agosto'), ('SEPTIEMBRE', 'Septiembre'), ('OCTUBRE', 'Octubre'), ('NOVIEMBRE', 'Noviembre'), ('DICIEMBRE', 'Diciembre')], default='ENERO', max_length=10)),
                ('year_of', models.CharField(max_length=4)),
                ('year_to', models.CharField(max_length=4)),
                ('file', models.FileField(blank=True, null=True, upload_to='administrativos/%Y/%m/%d')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.departaments')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.document_type')),
                ('personal_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.personals')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.serials')),
                ('sub_serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.sub_serial')),
            ],
            options={
                'verbose_name': 'Expedient',
                'verbose_name_plural': 'Expedients',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='administrativos/%Y/%m/%d')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.document_type')),
                ('expedients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.expedients')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='document_type',
            name='sub_serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.sub_serial'),
        ),
    ]
