# Generated by Django 4.0.6 on 2022-08-03 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personals',
            name='expedient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.expedients'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expedients',
            name='personal_info',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
