# Generated by Django 4.0.6 on 2022-08-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_expedients_personal_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedients',
            name='personal_info',
            field=models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, max_length=1),
        ),
    ]
