# Generated by Django 4.0.6 on 2022-08-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_expedients_personal_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='expedients',
            name='personal_info',
            field=models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0),
        ),
    ]
