# Generated by Django 4.0.6 on 2022-07-30 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('responsable', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Departament',
                'verbose_name_plural': 'Departaments',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Document_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tipo Documento')),
            ],
            options={
                'verbose_name': 'Document_type',
                'verbose_name_plural': 'Documents_types',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Serials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Serie Documental')),
            ],
            options={
                'verbose_name': 'Serial',
                'verbose_name_plural': 'Serials',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=20)),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexing.departaments')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Sub_serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Sub serie documental')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexing.serials')),
            ],
            options={
                'verbose_name': 'Sub_serial',
                'verbose_name_plural': 'Sub_serials',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=20)),
                ('data_type', models.CharField(default='TEXTO', max_length=30)),
                ('status', models.CharField(default='0', max_length=1)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexing.templates')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Expedients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AREA', 'Area'), ('ARCHIVO', 'Archivo'), ('LOGICSA', 'Logicsa')], default='AREA', max_length=10)),
                ('codigo_archivo', models.CharField(max_length=10)),
                ('codigo_cliente', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of', models.DateField(blank=True, null=True, verbose_name='YYYY-MM-DD')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='YYYY-MM-DD')),
                ('month_of', models.CharField(choices=[('ENERO', 'Enero'), ('FEBRERO', 'Febrero'), ('MARZO', 'Marzo'), ('ABRIL', 'Abril'), ('MAYO', 'Mayo'), ('JUNIO', 'Junio'), ('JULIO', 'Julio'), ('AGOSTO', 'Agosto'), ('SEPTIEMBRE', 'Septiembre'), ('OCTUBRE', 'Octubre'), ('NOVIEMBRE', 'Noviembre'), ('DICIEMBRE', 'Diciembre')], default='ENERO', max_length=10)),
                ('month_to', models.CharField(choices=[('ENERO', 'Enero'), ('FEBRERO', 'Febrero'), ('MARZO', 'Marzo'), ('ABRIL', 'Abril'), ('MAYO', 'Mayo'), ('JUNIO', 'Junio'), ('JULIO', 'Julio'), ('AGOSTO', 'Agosto'), ('SEPTIEMBRE', 'Septiembre'), ('OCTUBRE', 'Octubre'), ('NOVIEMBRE', 'Noviembre'), ('DICIEMBRE', 'Diciembre')], default='ENERO', max_length=10)),
                ('year_of', models.CharField(max_length=4)),
                ('year_to', models.CharField(max_length=4)),
                ('file', models.FileField(blank=True, null=True, upload_to='administrativos/%Y/%m/%d')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexing.departaments')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexing.document_type')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexing.serials')),
                ('sub_serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexing.sub_serial')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexing.templates')),
            ],
            options={
                'verbose_name': 'Expedient',
                'verbose_name_plural': 'Expedients',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of', models.DateField(blank=True, null=True, verbose_name='YYYY-MM-DD')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='YYYY-MM-DD')),
                ('month_of', models.CharField(choices=[('ENERO', 'Enero'), ('FEBRERO', 'Febrero'), ('MARZO', 'Marzo'), ('ABRIL', 'Abril'), ('MAYO', 'Mayo'), ('JUNIO', 'Junio'), ('JULIO', 'Julio'), ('AGOSTO', 'Agosto'), ('SEPTIEMBRE', 'Septiembre'), ('OCTUBRE', 'Octubre'), ('NOVIEMBRE', 'Noviembre'), ('DICIEMBRE', 'Diciembre')], default='ENERO', max_length=10)),
                ('month_to', models.CharField(choices=[('ENERO', 'Enero'), ('FEBRERO', 'Febrero'), ('MARZO', 'Marzo'), ('ABRIL', 'Abril'), ('MAYO', 'Mayo'), ('JUNIO', 'Junio'), ('JULIO', 'Julio'), ('AGOSTO', 'Agosto'), ('SEPTIEMBRE', 'Septiembre'), ('OCTUBRE', 'Octubre'), ('NOVIEMBRE', 'Noviembre'), ('DICIEMBRE', 'Diciembre')], default='ENERO', max_length=10)),
                ('year_of', models.CharField(max_length=4)),
                ('year_to', models.CharField(max_length=4)),
                ('file', models.FileField(blank=True, null=True, upload_to='administrativos/%Y/%m/%d')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexing.document_type')),
                ('expedients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexing.expedients')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexing.templates')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='document_type',
            name='sub_serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexing.sub_serial'),
        ),
        migrations.CreateModel(
            name='Detail_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=300)),
                ('data_type', models.CharField(max_length=15)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexing.documents')),
                ('expedients', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexing.expedients')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexing.fields')),
            ],
            options={
                'verbose_name': 'Detail_Field',
                'verbose_name_plural': 'Detail_Fiels',
                'ordering': ('id',),
            },
        ),
    ]
